---
title: Query Open Targets
subtitle: Ayush Noori
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include = FALSE}
# knitr::opts_chunk$set(message=FALSE, warning=FALSE)
```

# Dependencies

Load requisite packages and define directories.

```{r load-packages, message=FALSE, warning=FALSE}

# data manipulation
library(data.table)
library(purrr)
library(magrittr)

# excel manipulation
library(openxlsx)

# string manipulation
library(stringi)

# GraphQL API
library(httr)
library(jsonlite)

# utilities
library(brainstorm)

```

Note that directories are relative to the R project path.

```{r define-directores}

# set directories
otdir = file.path("Data", "2 - Open Targets")
ddir = file.path("Results", "1 - Query Drugs at FDA")
rdir = file.path("Results", "2 - Query Open Targets")

```

# Read Data

First, read datasets for analysis.

```{r read-data}

# read parsed Drugs at FDA data
flist = list.files(ddir, pattern = "*.csv")
dat = map(flist, ~fread(file.path(ddir, .x)))
names(dat) = gsub(".csv", "", map(strsplit(flist, " - "), 2))
dat = dat[c(2, 3, 1)]

```

# Query Open Targets

Now, query Open Targets database.

```{r query-targets}

# set gene ID variable
gene_id = "ENSG00000091831"

# build query string
query_string = "
  query target($ensemblId: String!){
    target(ensemblId: $ensemblId){
      id
      approvedSymbol
      approvedName
      bioType
      genomicLocation{
        chromosome
        start
        end
        strand
      }
    }
  }
"

# set base URL of GraphQL API endpoint
base_url = "https://api.platform.opentargets.org/api/v4/graphql"

# Set variables object of arguments to be passed to endpoint
variables = list("ensemblId" = gene_id)

# Construct POST request body object with query string and variables
post_body = list(query = query_string, variables = variables)

# Perform POST request
res = httr::POST(url = base_url, body = post_body, encode = "json") %>%
  httr::content(as = "text", encoding = "UTF-8") %>%
  fromJSON() %>% .[[1]]

```
